server:
  port: 8080

spring:
  data:
    mongodb:
      database: ecommerce-coder
      host: localhost
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: ecommercejavabackend@gmail.com
    password: jomubhmppvtsgyjl
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true